#!/usr/bin/env python3
"""
emoji2lvgl.py
=============
將 Twemoji (Twitter Open Emoji, CC-BY 4.0) 的 PNG 圖示
下載、縮放後轉換成 LVGL v9 ARGB8888 C 陣列。

用法:
  pip install pillow requests
  python emoji2lvgl.py

輸出:
  src/sprites/img_player.c / .h
  src/sprites/img_enemy1.c / .h
  ...
  src/sprites/sprites.h   (統一 include 標頭)
"""

import os, sys, io, struct
import ssl
import urllib.request

# MSYS2 Python 沒有系統 CA 憑證，建立不驗證 SSL 的 context（下載可信 CDN 是安全的）
_ssl_ctx = ssl.create_default_context()
_ssl_ctx.check_hostname = False
_ssl_ctx.verify_mode = ssl.CERT_NONE

try:
    import requests
    USE_REQUESTS = True
except ImportError:
    USE_REQUESTS = False

try:
    from PIL import Image
except ImportError:
    print("ERROR: 請先安裝 Pillow:  pip install pillow")
    sys.exit(1)

# ── 輸出目錄 ──────────────────────────────────────────────────────────────────
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "src", "sprites")

# ── Twemoji CDN（版本固定避免格式改變）────────────────────────────────────────
TWEMOJI_BASE = "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/"

# ── Sprite 清單 ───────────────────────────────────────────────────────────────
# (name, twemoji_codepoint(s), width, height, flip_h)
# flip_h=True → 水平翻轉，讓飛機面向右邊
SPRITES = [
    # ──── 玩家 ────
    ("img_player",    "2708",   52, 34, True),   # ✈ 飛機（翻轉朝右）
    ("img_wingman",   "1f6e9",  34, 24, True),   # 🛩 小飛機（翻轉朝右）

    # ──── 普通敵機 ────
    ("img_enemy_ufo",    "1f6f8", 38, 38, False),  # 🛸 飛碟
    ("img_enemy_rocket", "1f680", 34, 40, False),  # 🚀 火箭
    ("img_enemy_alien",  "1f47e", 34, 34, False),  # 👾 外星人

    # ──── Boss ────
    ("img_boss1",  "1f916",  76, 76, False),  # 🤖 Robot
    ("img_boss2",  "1f479",  84, 76, False),  # 👹 Ogre

    # ──── 特效 ────
    ("img_explosion", "1f4a5", 52, 52, False),  # 💥 爆炸
    ("img_pickup",    "1f340", 30, 30, False),  # 🍀 補給道具

    # ──── UI ────
    ("img_heart",  "2764",  22, 20, False),  # ❤ 血量圖示
    ("img_bomb",   "1f4a3", 20, 20, False),  # 💣 Boss 子彈
]

# ── LVGL v9 常數 ──────────────────────────────────────────────────────────────
LV_IMAGE_HEADER_MAGIC   = 0x19
LV_COLOR_FORMAT_ARGB8888 = 0x10   # lv_color_format_t 中的 enum 值


# ── 下載 Twemoji PNG ──────────────────────────────────────────────────────────
def download_png(codepoint: str) -> bytes:
    """
    嘗試多個 codepoint 變體（帶/不帶 fe0f variation selector）
    """
    candidates = [codepoint]
    # 如果沒有 -fe0f 結尾，試著加上去
    if not codepoint.endswith("-fe0f"):
        candidates.append(codepoint + "-fe0f")
    # 如果有 -fe0f，也試著去掉
    if "-fe0f" in codepoint:
        candidates.append(codepoint.replace("-fe0f", ""))

    last_err = None
    for cp in candidates:
        url = TWEMOJI_BASE + cp + ".png"
        print(f"    GET {url}")
        try:
            if USE_REQUESTS:
                r = requests.get(url, timeout=15, verify=False)
                r.raise_for_status()
                return r.content
            else:
                req = urllib.request.Request(url, headers={"User-Agent": "emoji2lvgl/1.0"})
                with urllib.request.urlopen(req, timeout=15, context=_ssl_ctx) as resp:
                    return resp.read()
        except Exception as e:
            last_err = e
    raise RuntimeError(f"下載失敗 ({codepoint}): {last_err}")


# ── PIL RGBA → LVGL ARGB8888 bytes ───────────────────────────────────────────
def rgba_to_lvgl(img: Image.Image) -> bytes:
    """
    PIL RGBA (R,G,B,A) → LVGL ARGB8888 memory layout: B,G,R,A (little-endian)
    """
    raw = bytearray(img.width * img.height * 4)
    idx = 0
    for r, g, b, a in img.getdata():
        raw[idx]   = b
        raw[idx+1] = g
        raw[idx+2] = r
        raw[idx+3] = a
        idx += 4
    return bytes(raw)


# ── 產生 C 原始碼 ─────────────────────────────────────────────────────────────
def make_c_source(name: str, img: Image.Image) -> tuple:
    w, h = img.size
    pixel_data = rgba_to_lvgl(img)
    stride     = w * 4
    data_size  = len(pixel_data)

    # 每行 16 bytes，格式化成 0xNN, ...
    lines = []
    for i in range(0, data_size, 16):
        chunk = pixel_data[i:i+16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    hex_block = "\n".join(lines)

    c_src = f"""\
/**
 * Auto-generated by emoji2lvgl.py
 * Source: Twemoji  https://twemoji.twitter.com/  (CC-BY 4.0)
 * Size: {w} x {h} px,  ARGB8888,  {data_size} bytes
 */
#include "lvgl/lvgl.h"
#include "{name}.h"

static const uint8_t _{name}_data[{data_size}] = {{
{hex_block}
}};

const lv_image_dsc_t {name} = {{
    .header = {{
        .magic  = LV_IMAGE_HEADER_MAGIC,    /* 0x19 */
        .cf     = LV_COLOR_FORMAT_ARGB8888, /* 0x10 */
        .flags  = 0,
        .w      = {w},
        .h      = {h},
        .stride = {stride},
    }},
    .data_size = {data_size},
    .data      = _{name}_data,
}};
"""
    h_src = f"""\
#ifndef {name.upper()}_H
#define {name.upper()}_H

#include "lvgl/lvgl.h"

LV_IMG_DECLARE({name});

#endif /* {name.upper()}_H */
"""
    return c_src, h_src


# ── 主程式 ────────────────────────────────────────────────────────────────────
def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    success = []
    failed  = []

    for (name, codepoint, tw, th, flip_h) in SPRITES:
        print(f"\n[{name}]  U+{codepoint.upper()}  →  {tw}×{th} px")
        try:
            raw  = download_png(codepoint)
            img  = Image.open(io.BytesIO(raw)).convert("RGBA")
            img  = img.resize((tw, th), Image.LANCZOS)
            if flip_h:
                img = img.transpose(Image.FLIP_LEFT_RIGHT)

            c_src, h_src = make_c_source(name, img)

            c_path = os.path.join(OUTPUT_DIR, f"{name}.c")
            h_path = os.path.join(OUTPUT_DIR, f"{name}.h")
            with open(c_path, "w", encoding="utf-8") as f:
                f.write(c_src)
            with open(h_path, "w", encoding="utf-8") as f:
                f.write(h_src)

            # 同時儲存 PNG 供預覽
            img.save(os.path.join(OUTPUT_DIR, f"{name}.png"))

            print(f"    OK  →  {c_path}  ({data_size(c_src)} bytes pixel data)")
            success.append(name)
        except Exception as e:
            print(f"    FAIL: {e}")
            failed.append((name, str(e)))

    # 產生統一 include 標頭 src/sprites/sprites.h
    all_names = [s[0] for s in SPRITES if s[0] in success]
    includes  = "\n".join(f'#include "{n}.h"' for n in all_names)
    sprites_h = f"""\
/**
 * sprites.h  —  unified include for all LVGL image sprites
 * Auto-generated by emoji2lvgl.py
 */
#ifndef SPRITES_H
#define SPRITES_H

{includes}

#endif /* SPRITES_H */
"""
    with open(os.path.join(OUTPUT_DIR, "sprites.h"), "w", encoding="utf-8") as f:
        f.write(sprites_h)

    print(f"\n{'='*60}")
    print(f"完成！成功 {len(success)} 個，失敗 {len(failed)} 個")
    print(f"輸出目錄: {OUTPUT_DIR}")
    if failed:
        print("\n失敗清單:")
        for n, e in failed:
            print(f"  {n}: {e}")


def data_size(c_src: str) -> int:
    """從 C 原始碼中讀出 data_size 的數字"""
    import re
    m = re.search(r'\.data_size = (\d+)', c_src)
    return int(m.group(1)) if m else 0


if __name__ == "__main__":
    main()
