/**
 * sprites.h  —  unified include for all LVGL image sprites
 * Auto-generated by emoji2lvgl.py
 */
#ifndef SPRITES_H
#define SPRITES_H

#include "img_player.h"
#include "img_wingman.h"
#include "img_enemy_ufo.h"
#include "img_enemy_rocket.h"
#include "img_enemy_alien.h"
#include "img_boss1.h"
#include "img_boss2.h"
#include "img_explosion.h"
#include "img_pickup.h"
#include "img_heart.h"
#include "img_bomb.h"

#endif /* SPRITES_H */
